apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-deployment
  namespace: backoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backoffice
  template:
    metadata:
      labels:
        app: backoffice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: backoffice
          image: ghcr.io/najehch/surveypro-backoffice:latest
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "http://backend-service.db-backend.svc.cluster.local:3000"
          ports:
            - containerPort: 4200
          resources:
            requests:
              cpu: "450m"
              memory: "712Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
