apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontoffice-deployment
  namespace: frontoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontoffice
  template:
    metadata:
      labels:
        app: frontoffice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontoffice
          image: ghcr.io/najehch/surveypro-frontoffice:latest
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "http://backend-service.db-backend.svc.cluster.local:3000/"
          ports:
            - containerPort: 4209
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
