apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontoffice-deployment
  namespace: frontoffice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontoffice
  template:
    metadata:
      labels:
        app: frontoffice
    spec:
      containers:
        - name: frontoffice
          image: registry.gitlab.com/najehch/surveypro/frontoffice:latest
          ports:
            - containerPort: 4209
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"