apiVersion: v1
kind: Service
metadata:
  name: frontoffice-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: frontoffice
  ports:
    - port: 4209
      targetPort: 4209
      nodePort: 30081