# Optional: replace the .dockerconfigjson with your base64-encoded docker config
# Prefer: `kubectl create secret docker-registry ghcr-secret --docker-server=ghcr.io --docker-username=<USERNAME> --docker-password=<PAT> -n db-backend`
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: db-backend
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: PLACEHOLDER_BASE64_DOCKERCONFIGJSON